
services:
  backend:
    build: ./server  # Path to the Dockerfile in the server folder
    ports:
      - "3000:3000"  # Expose port 3000
    volumes:
      - ./server:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_portal
    depends_on:
      - postgres

  frontend:
    build: ./client  # Path to the Dockerfile in the client folder
    ports:
      - "3001:3001"  # Expose port 3001
    volumes:
      - ./client:/app
    depends_on:
      - backend

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
